CREATE TABLE `SPRING_SESSION` (
  `PRIMARY_KEY` VARCHAR(255) NOT NULL PRIMARY KEY,
  `SESSION_ID` VARCHAR(255) NOT NULL UNIQUE KEY,
  `SESSION_DATA` BLOB NOT NULL,
  `LAST_ACCESS_TIME` BIGINT NOT NULL,
  `MAX_INACTIVE_INTERVAL` BIGINT NOT NULL,
  `EXPIRY_TIME` BIGINT NOT NULL
);

INSERT INTO roles (name)
VALUES ('user');

INSERT INTO roles (name)
VALUES ('administrator');
